name: Shell Commends

on: push

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "hello world!"
      - name: multiline script
        run: |
          node -v
          npm -v

  run-python-commands:
    runs-on: ubuntu-latest
    steps:
      - name: python command
        run: |
          import platform
          print(platform.processor())
